version: '2'
services:
    manle-app:
        image: manle
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://manle-mysql:3306/manle?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    manle-mysql:
        extends:
            file: mysql.yml
            service: manle-mysql
